//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRM_Yu.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Client
    {
        public int Client_Id { get; set; }
        public string LastName { get; set; }
        public string FirstName { get; set; }
        public Nullable<int> DOB_YYYY { get; set; }
        public Nullable<int> DOB_Month { get; set; }
        public Nullable<int> DOB_Date { get; set; }
    }
}
